import { createBadgeManifest, renderBadgeSvg } from "./badge";
import { assertPublicManifestSafe } from "./privacy";
import { sampleAggregate, sampleOutcomes } from "./sample";

it("creates a public-safe manifest with at most three chips", () => {
  const manifest = createBadgeManifest(sampleAggregate, sampleOutcomes);
  expect(manifest.chips.length).toBeLessThanOrEqual(3);
  expect(manifest.title).toBe("Codex Merit Token");
  expect(manifest.profileName).toBe("Mission Commander");
  expect(manifest.heroMetric.label).toBe("Verified Codex hours");
  expect(manifest.heroMetric.value).toBe("257");
  expect(manifest.shareUrl).toBe("https://x.com/anthonydibe");
  expect(manifest.confidenceStrip).toContain("Codex Merit Card");
  expect(() => assertPublicManifestSafe(manifest)).not.toThrow();
});

it("renders a deterministic square svg with no local paths", () => {
  const manifest = createBadgeManifest(sampleAggregate, sampleOutcomes);
  const svg = renderBadgeSvg(manifest, 1080);
  expect(svg).toContain('width="1080"');
  expect(svg).toContain('height="1080"');
  expect(svg).toContain('viewBox="0 0 1080 1080"');
  expect(svg).toContain("Mission Commander");
  expect(svg).toContain("Verified Codex hours");
  expect(svg).toContain('id="holographic-edge"');
  expect(svg).toContain("holoEdge");
  expect(svg).toContain('id="signal-stack"');
  expect(svg).toContain('id="security-glyph"');
  expect(svg).toContain('id="holographic-label"');
  expect(svg).toContain('id="holo-rosette"');
  expect(svg).toContain('id="crypto-frame"');
  expect(svg).toContain('id="crypto-hash-strip"');
  expect(svg).toContain('id="crypto-checksum-grid"');
  expect(svg).toContain('id="profile-url-qr"');
  expect(svg).toContain('data-profile-url="https://x.com/anthonydibe"');
  expect(svg).toContain('data-quiet-modules="4"');
  expect(svg).toContain('width="135" height="135" fill="#ffffff"');
  expect(svg).toContain("holoRainbow");
  expect(svg).toContain("holoLattice");
  expect(svg).toContain("PROFILE URL");
  expect(svg).toContain('id="metric-dock"');
  expect(svg).not.toContain('id="rank-plaque"');
  expect(svg).not.toContain("rankPlate");
  expect(svg).not.toContain("rankEdge");
  expect(svg).not.toContain("M0 76C74 26 160 24 238 76");
  expect(svg).not.toContain("M22 0H180L208 28V74");
  expect(svg).not.toContain("holoGlyph");
  expect(svg).not.toContain("cryptoFoil");
  expect(svg).not.toContain("crypto-guilloche");
  expect(svg).not.toContain("crypto-rosette");
  expect(svg).not.toContain("#42d8d4");
  expect(svg).not.toContain("PRIVACY CHECK");
  expect(svg).not.toContain("SHARE SAFE");
  expect(svg).not.toContain("NO PROMPTS");
  expect(svg).not.toContain("PUBLIC-SAFE");
  expect(svg).not.toContain("/Users/");
  expect(svg).not.toContain("undefined");
});
